"""Copic Sketch marker palette — 350 colors, 18 groups.
Extracted from `.claude/agents/visual-design-engineer/assets/colors/copic-color-reference.html`.
Each group: {id, name, desc, colors: [(code, hex, name), ...]}.
"""

COPIC_PALETTE = [
    {
        "id": 'special', "name": 'Special', "desc": 'Colorless & Black',
        "colors": [
            ('0', '#FFFFFF', 'Colorless Blender'),
            ('100', '#312B2B', 'Black'),
            ('110', '#030708', 'Special Black'),
        ],
    },
    {
        "id": 'b', "name": 'B', "desc": 'Blue',
        "colors": [
            ('B0000', '#F0F9FE', 'Pale Celestine'),
            ('B000', '#E6F4F5', 'Pale Porcelain Blue'),
            ('B00', '#DDF0F4', 'Frost Blue'),
            ('B01', '#D6EEF2', 'Mint Blue'),
            ('B02', '#B3E3F1', "Robin's Egg Blue"),
            ('B04', '#73CFE6', 'Tahitian Blue'),
            ('B05', '#40C5E6', 'Process Blue'),
            ('B06', '#00B3E6', 'Peacock Blue'),
            ('B12', '#C8E6F0', 'Ice Blue'),
            ('B14', '#71CFEB', 'Light Blue'),
            ('B16', '#00BCEA', 'Cyanine Blue'),
            ('B18', '#1D8ACB', 'Lapis Lazuli'),
            ('B21', '#DBEDF9', 'Baby Blue'),
            ('B23', '#92C2E8', 'Phthalo Blue'),
            ('B24', '#8ACEF3', 'Sky'),
            ('B26', '#65B3E3', 'Cobalt Blue'),
            ('B28', '#196DB6', 'Royal Blue'),
            ('B29', '#0177C1', 'Ultramarine'),
            ('B32', '#E2EFF7', 'Pale Blue'),
            ('B34', '#82C3ED', 'Manganese Blue'),
            ('B37', '#156FA4', 'Antwerp Blue'),
            ('B39', '#2B64A9', 'Prussian Blue'),
            ('B41', '#E2F0FB', 'Powder Blue'),
            ('B45', '#75C0EA', 'Smoky Blue'),
            ('B52', '#ADCDDC', 'Soft Greenish Blue'),
            ('B60', '#DAE1F3', 'Light Blue Violet'),
            ('B63', '#A7BBE0', 'Light Hydrangea'),
            ('B66', '#6888C5', 'Clematis'),
            ('B69', '#2165AE', 'Stratospheric Blue'),
            ('B79', '#3B479D', 'Iris'),
            ('B91', '#D5E2EB', 'Pale Grayish Blue'),
            ('B93', '#95C1DA', 'Light Crockery Blue'),
            ('B95', '#60C5CF', 'Light Grayish Cobalt'),
            ('B97', '#457A9A', 'Night Blue'),
            ('B99', '#0F547E', 'Agate'),
        ],
    },
    {
        "id": 'bg', "name": 'BG', "desc": 'Blue Green',
        "colors": [
            ('BG0000', '#EFF8F3', 'Snow Green'),
            ('BG000', '#E5F4ED', 'Pale Aqua'),
            ('BG01', '#C7E6FA', 'Aqua Blue'),
            ('BG02', '#C6E8EA', 'New Blue'),
            ('BG05', '#1DB8CE', 'Holiday Blue'),
            ('BG07', '#1DB8CE', 'Petroleum Blue'),
            ('BG09', '#DCF0EF', 'Blue Green'),
            ('BG10', '#DCF0EF', 'Cool Shadow'),
            ('BG11', '#CEEBF1', 'Moon White'),
            ('BG13', '#C4E7E9', 'Mint Green'),
            ('BG15', '#A0D9D2', 'Aqua'),
            ('BG18', '#37C0B0', 'Teal Blue'),
            ('BG23', '#BDE5DD', 'Coral Sea'),
            ('BG32', '#BCE2D7', 'Aqua Mint'),
            ('BG34', '#A3DAD7', 'Horizon Green'),
            ('BG45', '#AFDFDF', 'Nile Blue'),
            ('BG49', '#00B6B9', 'Duck Blue'),
            ('BG53', '#ACCFD1', 'Ice Mint'),
            ('BG57', '#64BEBE', 'Jasper'),
            ('BG70', '#DAECEE', 'Ocean Mist'),
            ('BG72', '#74B8BB', 'Ice Ocean'),
            ('BG75', '#59918E', 'Abyss Green'),
            ('BG78', '#49706B', 'Bronze'),
            ('BG90', '#BAC1B9', 'Gray Sky'),
            ('BG93', '#BAC1B9', 'Green Gray'),
            ('BG96', '#81A291', 'Anti Blue Green'),
            ('BG99', '#6E9B87', 'Flagstone Blue'),
        ],
    },
    {
        "id": 'bv', "name": 'BV', "desc": 'Blue Violet',
        "colors": [
            ('BV0000', '#EAE7F2', 'Pale Thistle'),
            ('BV000', '#EAE7F2', 'Iridescent Mauve'),
            ('BV00', '#E0DCED', 'Mauve Shadow'),
            ('BV01', '#C4C9E6', 'Viola'),
            ('BV02', '#AAB8DB', 'Prune'),
            ('BV04', '#7C97CE', 'Blue Berry'),
            ('BV08', '#EAE7F2', 'Blue Violet'),
            ('BV11', '#D4D2E8', 'Soft Violet'),
            ('BV13', '#8491C8', 'Hydrangea Blue'),
            ('BV17', '#6E84BD', 'Deep Reddish Blue'),
            ('BV20', '#CFDBF1', 'Dull Lavender'),
            ('BV23', '#B1C0DD', 'Grayish Lavender'),
            ('BV25', '#8184A7', 'Grayish Violet'),
            ('BV29', '#384558', 'Slate'),
            ('BV31', '#EAE7F2', 'Pale Lavender'),
            ('BV34', '#9FA7BC', 'Bluebell'),
        ],
    },
    {
        "id": 'c', "name": 'C', "desc": 'Cool Gray',
        "colors": [
            ('C00', '#E0E7ED', 'Cool Gray 00'),
            ('C0', '#E0E7ED', 'Cool Gray 0'),
            ('C1', '#DAE3E8', 'Cool Gray 1'),
            ('C2', '#CCD7DD', 'Cool Gray 2'),
            ('C3', '#C1CCD2', 'Cool Gray 3'),
            ('C4', '#92A0AB', 'Cool Gray 4'),
            ('C5', '#92A0AB', 'Cool Gray 5'),
            ('C6', '#637079', 'Cool Gray 6'),
            ('C7', '#637079', 'Cool Gray 7'),
            ('C8', '#535D66', 'Cool Gray 8'),
            ('C9', '#3C474D', 'Cool Gray 9'),
            ('C10', '#202B31', 'Cool Gray 10'),
        ],
    },
    {
        "id": 'e', "name": 'E', "desc": 'Earth / Skin / Brown',
        "colors": [
            ('E0000', '#FFFAF4', 'Floral White'),
            ('E000', '#FEF5EE', 'Pale Fruit Pink'),
            ('E00', '#FDF3EA', 'Cotton Pearl'),
            ('E01', '#FFEEE4', 'Pink Flamingo'),
            ('E02', '#FEECE0', 'Fruit Pink'),
            ('E04', '#E4BCC4', 'Lipstick Natural'),
            ('E07', '#CC816A', 'Light Mahogany'),
            ('E08', '#CA6553', 'Brown'),
            ('E09', '#D96A4F', 'Burnt Sienna'),
            ('E11', '#FEE9D6', 'Bareley Beige'),
            ('E13', '#E9C5AF', 'Light Suntan'),
            ('E15', '#FBBB8D', 'Dark Suntan'),
            ('E17', '#B85F57', 'Reddish Brass'),
            ('E18', '#88534D', 'Copper'),
            ('E19', '#C45238', 'Redwood'),
            ('E21', '#FDE2C7', 'Soft Sun'),
            ('E23', '#ECCAB1', 'Hazelnut'),
            ('E25', '#D2A482', 'Caribe Cocoa'),
            ('E27', '#997663', 'Africano'),
            ('E29', '#884636', 'Burnt Umber'),
            ('E30', '#F7F0D6', 'Bisque'),
            ('E31', '#F2E6CE', 'Brick Beige'),
            ('E33', '#F3D2B1', 'Sand'),
            ('E34', '#F0CAA6', 'Toast'),
            ('E35', '#E6C3A3', 'Chamois'),
            ('E37', '#CC9159', 'Sepia'),
            ('E39', '#C5743F', 'Leather'),
            ('E40', '#F2E8DC', 'Brick White'),
            ('E41', '#FEF1E1', 'Pearl White'),
            ('E42', '#F3EAD9', 'Sand White'),
            ('E43', '#E8DABD', 'Dull Ivory'),
            ('E44', '#8A6E59', 'Clay'),
            ('E47', '#8A6E59', 'Dark Brown'),
            ('E49', '#634C3C', 'Dark Bark'),
            ('E50', '#F4EBF0', 'Egg Shell'),
            ('E51', '#FEECD6', 'Milky White'),
            ('E53', '#F1DFB9', 'Raw Silk'),
            ('E55', '#F1DFB9', 'Light Camel'),
            ('E57', '#B18558', 'Light Walnut'),
            ('E59', '#9A7F6C', 'Walnut'),
            ('E70', '#EFEAE6', 'Ash Rose'),
            ('E71', '#A1847C', 'Champagne'),
            ('E74', '#A1847C', 'Cocoa Brown'),
            ('E77', '#7F604E', 'Maroon'),
            ('E79', '#4A2C22', 'Cashew'),
            ('E81', '#F0E6C2', 'Ivory'),
            ('E84', '#AE9F80', 'Khaki'),
            ('E87', '#6F604D', 'Fig'),
            ('E89', '#5A4939', 'Pecan'),
            ('E93', '#FED2B9', 'Tea Rose'),
            ('E95', '#FCBC7E', 'Tea Orange'),
            ('E97', '#B46034', 'Deep Orange'),
            ('E99', '#B46034', 'Baked Clay'),
        ],
    },
    {
        "id": 'f', "name": 'F', "desc": 'Fluorescent',
        "colors": [
            ('FRV1', '#F5A3C7', 'Fluorescent Pink'),
            ('FV2', '#7F74B6', 'Fluorescent Dull Violet'),
            ('FY1', '#FFF697', 'Fluorescent Yellow Orange'),
            ('FYR1', '#FECC99', 'Fluorescent Orange'),
        ],
    },
    {
        "id": 'g', "name": 'G', "desc": 'Green',
        "colors": [
            ('G0000', '#F1F7F3', 'Crystal Opal'),
            ('G000', '#EAF5ED', 'Pale Green'),
            ('G00', '#E3F2ED', 'Jade Green'),
            ('G02', '#CFE8D3', 'Spectrum Green'),
            ('G03', '#B6DA9C', 'Meadow Green'),
            ('G05', '#69C07B', 'Emerald Green'),
            ('G07', '#7BC576', 'Nile Green'),
            ('G09', '#7AC465', 'Veronese Green'),
            ('G12', '#D2E8C4', 'Sea Green'),
            ('G14', '#97CF90', 'Apple Green'),
            ('G16', '#60C198', 'Malachite'),
            ('G17', '#14B37D', 'Forest Green'),
            ('G19', '#2DB98A', 'Bright Parrot Green'),
            ('G20', '#EDF6DB', 'Wax White'),
            ('G21', '#C4E4CD', 'Lime Green'),
            ('G24', '#C3E0B4', 'Willow'),
            ('G28', '#119462', 'Ocean Green'),
            ('G29', '#197C5D', 'Pine Tree Green'),
            ('G40', '#E4F1DF', 'Dim Green'),
            ('G43', '#D7E7A8', 'Pistachio'),
            ('G82', '#CCDAB9', 'Spring Dim Green'),
            ('G85', '#9DC3AA', 'Verdigris'),
            ('G94', '#98A786', 'Grayish Olive'),
            ('G99', '#5F7E3A', 'Olive'),
        ],
    },
    {
        "id": 'n', "name": 'N', "desc": 'Neutral Gray',
        "colors": [
            ('N0', '#ECEEED', 'Neutral Gray 0'),
            ('N1', '#E2E3E5', 'Neutral Gray 1'),
            ('N2', '#DADBDD', 'Neutral Gray 2'),
            ('N3', '#D1D2D4', 'Neutral Gray 3'),
            ('N4', '#BCBDC1', 'Neutral Gray 4'),
            ('N5', '#A8A9AD', 'Neutral Gray 5'),
            ('N6', '#949599', 'Neutral Gray 6'),
            ('N7', '#77787C', 'Neutral Gray 7'),
            ('N8', '#636466', 'Neutral Gray 8'),
            ('N9', '#4C4D4F', 'Neutral Gray 9'),
            ('N10', '#312F30', 'Neutral Gray 10'),
        ],
    },
    {
        "id": 'r', "name": 'R', "desc": 'Red',
        "colors": [
            ('R0000', '#FEF3EF', 'Pink Beryl'),
            ('R000', '#FEF0E7', 'Cherry White'),
            ('R00', '#FEEAE1', 'Pinkish White'),
            ('R01', '#FDE0D8', 'Pinkish Vanilla'),
            ('R02', '#FDD3C7', 'Rose Salmon'),
            ('R05', '#F6917B', 'Salmon Red'),
            ('R07', '#F26F39', 'Cadmium Red'),
            ('R08', '#F26754', 'Vermilion'),
            ('R11', '#FDE1D5', 'Pale Cherry Pink'),
            ('R12', '#FCD3C1', 'Light Tea Rose'),
            ('R14', '#F59B92', 'Light Rouge'),
            ('R17', '#F4846C', 'Lipstick Orange'),
            ('R20', '#FCD7CF', 'Blush'),
            ('R21', '#FAC1B6', 'Sardonyx'),
            ('R22', '#F8B7B1', 'Light Prawn'),
            ('R24', '#F27579', 'Prawn'),
            ('R27', '#F15062', 'Cadmium Red'),
            ('R29', '#ED174B', 'Lipstick Red'),
            ('R30', '#FCE3DF', 'Pale Yellowish Pink'),
            ('R32', '#FAC1BA', 'Peach'),
            ('R35', '#F27185', 'Coral'),
            ('R37', '#E86C74', 'Carmine'),
            ('R39', '#CB487A', 'Garnet'),
            ('R43', '#EE848E', 'Bougainvillaea'),
            ('R46', '#E04D69', 'Strong Red'),
            ('R56', '#D27C95', 'Currant'),
            ('R59', '#B74F70', 'Cardinal'),
            ('R81', '#F1C8D6', 'Rose Pink'),
            ('R83', '#F19CB9', 'Rose Mist'),
            ('R85', '#D36A93', 'Rose Red'),
            ('R89', '#7D2B42', 'Dark Red'),
        ],
    },
    {
        "id": 'rv', "name": 'RV', "desc": 'Red Violet',
        "colors": [
            ('RV0000', '#F2EAF5', 'Evening Primrose'),
            ('RV000', '#F4E2EE', 'Pale Purple'),
            ('RV00', '#F1DAEA', 'Water Lily'),
            ('RV02', '#FAD5E6', 'Sugared Almond Pink'),
            ('RV04', '#F6A3BF', 'Shock Pink'),
            ('RV06', '#F386AF', 'Cerise'),
            ('RV10', '#FDECF4', 'Pale Pink'),
            ('RV11', '#FBD6DD', 'Pink'),
            ('RV13', '#F9C9D7', 'Tender Pink'),
            ('RV14', '#F495B7', 'Begonia Pink'),
            ('RV17', '#DB7EB3', 'Deep Magenta'),
            ('RV19', '#D268AA', 'Red Violet'),
            ('RV21', '#FDE8E7', 'Light Pink'),
            ('RV23', '#F8BAC9', 'Pure Pink'),
            ('RV25', '#F493BE', 'Dog Rose Flower'),
            ('RV29', '#EF4880', 'Crimson'),
            ('RV32', '#FAD3CE', 'Shadow Pink'),
            ('RV34', '#F9AFAE', 'Dark Pink'),
            ('RV42', '#F8BBB6', 'Salmon Pink'),
            ('RV52', '#F9CADE', 'Cotton Candy'),
            ('RV55', '#E9A5CA', 'Hollyhock'),
            ('RV63', '#D09DAE', 'Begonia'),
            ('RV66', '#B86A84', 'Raspberry'),
            ('RV69', '#8B576E', 'Peony'),
            ('RV95', '#B684A1', 'Baby Blossoms'),
            ('RV99', '#5A4858', 'Argyle Purple'),
        ],
    },
    {
        "id": 't', "name": 'T', "desc": 'Toner Gray',
        "colors": [
            ('T0', '#ECEEED', 'Toner Gray 0'),
            ('T1', '#EAEAE8', 'Toner Gray 1'),
            ('T2', '#E0E0DE', 'Toner Gray 2'),
            ('T3', '#D1D2CC', 'Toner Gray 3'),
            ('T4', '#BCBBB9', 'Toner Gray 4'),
            ('T5', '#A8A7A3', 'Toner Gray 5'),
            ('T6', '#949590', 'Toner Gray 6'),
            ('T7', '#777674', 'Toner Gray 7'),
            ('T8', '#63645F', 'Toner Gray 8'),
            ('T9', '#4C4B49', 'Toner Gray 9'),
            ('T10', '#322E2D', 'Toner Gray 10'),
        ],
    },
    {
        "id": 'tg-tr', "name": 'TG / TR', "desc": 'Toner Variants',
        "colors": [
            ('TG13', '#D4E59F', 'Toner Green'),
            ('TR000', '#FEECD8', 'Toner Red'),
        ],
    },
    {
        "id": 'v', "name": 'V', "desc": 'Violet',
        "colors": [
            ('V0000', '#F0EDF6', 'Rose Quartz'),
            ('V000', '#E9E5F3', 'Pale Heath'),
            ('V01', '#E4C1D9', 'Heath'),
            ('V04', '#E6AACE', 'Lilac'),
            ('V05', '#E2A6CA', 'Azalea'),
            ('V06', '#CE95C2', 'Lavender'),
            ('V09', '#8754A1', 'Violet'),
            ('V12', '#EED7E9', 'Pale Lilac'),
            ('V15', '#D3A6CD', 'Mallow'),
            ('V17', '#A092C7', 'Amethyst'),
            ('V20', '#E2E0ED', 'Wisteria'),
            ('V22', '#B2B1D0', 'Ash Lavender'),
            ('V25', '#857FAD', 'Pale Blackberry'),
            ('V28', '#6B668E', 'Eggplant'),
            ('V91', '#E8C4D0', 'Pale Grape'),
            ('V93', '#E5C1DB', 'Early Grape'),
            ('V95', '#B77CA8', 'Light Grape'),
            ('V99', '#524358', 'Aubergine'),
        ],
    },
    {
        "id": 'w', "name": 'W', "desc": 'Warm Gray',
        "colors": [
            ('W00', '#F3F3EB', 'Warm Gray 00'),
            ('W0', '#ECECE4', 'Warm Gray 0'),
            ('W1', '#E7E7DF', 'Warm Gray 1'),
            ('W2', '#DDDDD5', 'Warm Gray 2'),
            ('W3', '#D2D2CA', 'Warm Gray 3'),
            ('W4', '#BCBDB7', 'Warm Gray 4'),
            ('W5', '#A8A9A4', 'Warm Gray 5'),
            ('W6', '#94958F', 'Warm Gray 6'),
            ('W7', '#777873', 'Warm Gray 7'),
            ('W8', '#63645F', 'Warm Gray 8'),
            ('W9', '#4C4D48', 'Warm Gray 9'),
            ('W10', '#302F2B', 'Warm Gray 10'),
        ],
    },
    {
        "id": 'y', "name": 'Y', "desc": 'Yellow',
        "colors": [
            ('Y0000', '#FEFEF4', 'Pale Chiffon'),
            ('Y000', '#FFFCE9', 'Pale Lemon'),
            ('Y00', '#FEFDDF', 'Barium Yellow'),
            ('Y02', '#F6F396', 'Canary Yellow'),
            ('Y04', '#EDE556', 'Acacia'),
            ('Y06', '#FEF56C', 'Yellow'),
            ('Y08', '#FEF200', 'Acid Yellow'),
            ('Y11', '#FFFBCC', 'Pale Yellow'),
            ('Y13', '#FBF7AE', 'Lemon Yellow'),
            ('Y15', '#FEE96C', 'Cadmium Yellow'),
            ('Y17', '#FFE455', 'Golden Yellow'),
            ('Y18', '#FEED55', 'Lightning Yellow'),
            ('Y19', '#FFE93E', 'Napoli Yellow'),
            ('Y21', '#FFEEC2', 'Buttercup Yellow'),
            ('Y23', '#FBE3B3', 'Yellowish Beige'),
            ('Y26', '#F0DD67', 'Mustard'),
            ('Y28', '#CAA869', 'Lionet Gold'),
            ('Y32', '#F9DEC0', 'Cashmere'),
            ('Y35', '#FFD879', 'Maize'),
            ('Y38', '#FFD274', 'Honey'),
        ],
    },
    {
        "id": 'yg', "name": 'YG', "desc": 'Yellow Green',
        "colors": [
            ('YG0000', '#F2F7E0', 'Lily White'),
            ('YG00', '#E6E69E', 'Mimosa Yellow'),
            ('YG01', '#E2EBB2', 'Green Bice'),
            ('YG03', '#DEEAAA', 'Yellow Green'),
            ('YG05', '#D6E592', 'Salad'),
            ('YG06', '#C4DF92', 'Yellowish Green'),
            ('YG07', '#A5CF4F', 'Acid Green'),
            ('YG09', '#82C566', 'Lettuce Green'),
            ('YG11', '#E5F0D0', 'Migrate Yellow'),
            ('YG17', '#72C156', 'Grass Green'),
            ('YG21', '#F7F6BE', 'Anise'),
            ('YG23', '#E6EB8F', 'New Leaf'),
            ('YG25', '#D0E17B', 'Celadon Green'),
            ('YG41', '#D5EBD4', 'Pale Cobalt Green'),
            ('YG45', '#B4DCB7', 'Cobalt Green'),
            ('YG61', '#D6E9D6', 'Pale Moss'),
            ('YG63', '#A0CAA2', 'Pea Green'),
            ('YG67', '#81BF8C', 'Moss'),
            ('YG91', '#DAD7AE', 'Putty'),
            ('YG93', '#D2D29C', 'Grayish Yellow'),
            ('YG95', '#CBC65E', 'Pale Olive'),
            ('YG97', '#958F03', 'Spanish Olive'),
            ('YG99', '#4E6A15', 'Marine Green'),
        ],
    },
    {
        "id": 'yr', "name": 'YR', "desc": 'Yellow Red (Orange)',
        "colors": [
            ('YR0000', '#FFF3E5', 'Pale Chiffon'),
            ('YR00', '#FED6BD', 'Powder Pink'),
            ('YR01', '#FEDAC2', 'Peach Puff'),
            ('YR02', '#FCDCC5', 'Light Orange'),
            ('YR04', '#FEC369', 'Chrome Orange'),
            ('YR07', '#F26F39', 'Cadmium Orange'),
            ('YR09', '#F15524', 'Chinese Orange'),
            ('YR12', '#FFE2A6', 'Loquat'),
            ('YR14', '#FEC84E', 'Caramel'),
            ('YR15', '#FBB884', 'Pumpkin Yellow'),
            ('YR16', '#FEB729', 'Apricot'),
            ('YR18', '#F26B3C', 'Sanguine'),
            ('YR20', '#FFE1BF', 'Yellowish Shade'),
            ('YR21', '#F5DDB1', 'Cream'),
            ('YR23', '#ECCF8B', 'Yellow Ochre'),
            ('YR24', '#F0CF64', 'Pale Sepia'),
            ('YR30', '#FEF2DA', 'Macadamia Nut'),
            ('YR31', '#FFDEA8', 'Light Reddish Yellow'),
            ('YR61', '#FDDAC4', 'Yellowish Skin Pink'),
            ('YR65', '#FAAE60', 'Atoll'),
            ('YR68', '#F37022', 'Orange'),
            ('YR82', '#FDC68D', 'Mellow Peach'),
        ],
    },
]
