"""Curated Copic palette sets, ported from copic-palettes.html.

35 named palettes grouped into five categories: soft, cool, earth, moody,
bold. Each palette is a tuple of (code, hex, name) entries — a small
themed group of 3-5 colors, distinct from the full 350-color Copic library
served by `copic_palette.py`.
"""

from __future__ import annotations


CATEGORIES: dict[str, dict[str, str]] = {
    "soft":  {"label": "Soft & Delicate",     "note": "15 palettes"},
    "cool":  {"label": "Cool & Atmospheric",  "note": "5 palettes"},
    "earth": {"label": "Earth & Organic",     "note": "6 palettes"},
    "moody": {"label": "Moody & Sophisticated", "note": "3 palettes"},
    "bold":  {"label": "Bold & Saturated",    "note": "6 palettes"},
}


CURATED_PALETTES: list[dict] = [
    # ── SOFT & DELICATE ─────────────────────────────────────
    {"category": "soft", "name": "Powdered Sugar",
     "desc": "The quietest possible four colors. Stationery, fine jewelry.",
     "colors": [
        ("Y0000",  "#FEFEF4", "Pale Chiffon"),
        ("E0000",  "#FFFAF4", "Floral White"),
        ("BG0000", "#EFF8F3", "Snow Green"),
        ("RV0000", "#F2EAF5", "Evening Primrose"),
    ]},
    {"category": "soft", "name": "Whisper",
     "desc": "Barely-there neutrals for whitespace-led layouts.",
     "colors": [
        ("W00",    "#F3F3EB", "Warm Gray 00"),
        ("E50",    "#F4EBF0", "Egg Shell"),
        ("G0000",  "#F1F7F3", "Crystal Opal"),
        ("BV0000", "#EAE7F2", "Pale Thistle"),
    ]},
    {"category": "soft", "name": "Vanilla Custard",
     "desc": "Pale cream and warm butter. Bakery, baby goods, paper goods.",
     "colors": [
        ("E0000", "#FFFAF4", "Floral White"),
        ("Y0000", "#FEFEF4", "Pale Chiffon"),
        ("Y11",   "#FFFBCC", "Pale Yellow"),
        ("E51",   "#FEECD6", "Milky White"),
    ]},
    {"category": "soft", "name": "Peach Veil",
     "desc": "Translucent warmth, sunrise through gauze.",
     "colors": [
        ("YR0000", "#FFF3E5", "Pale Chiffon"),
        ("R00",    "#FEEAE1", "Pinkish White"),
        ("E01",    "#FFEEE4", "Pink Flamingo"),
        ("E11",    "#FEE9D6", "Bareley Beige"),
    ]},
    {"category": "soft", "name": "Seafoam Pillow",
     "desc": "Hushed aquatics. Spa, skincare, infant.",
     "colors": [
        ("G00",   "#E3F2ED", "Jade Green"),
        ("BG000", "#E5F4ED", "Pale Aqua"),
        ("B00",   "#DDF0F4", "Frost Blue"),
        ("BG11",  "#CEEBF1", "Moon White"),
    ]},
    {"category": "soft", "name": "Morning Mist",
     "desc": "Cool dawn through condensation. Editorial calm, UI surfaces.",
     "colors": [
        ("C00",  "#E0E7ED", "Cool Gray 00"),
        ("B41",  "#E2F0FB", "Powder Blue"),
        ("BV20", "#CFDBF1", "Dull Lavender"),
        ("B91",  "#D5E2EB", "Pale Grayish Blue"),
    ]},
    {"category": "soft", "name": "Lavender Sigh",
     "desc": "Powdered violet, exhaled. Wedding, wellness, journaling.",
     "colors": [
        ("V0000", "#F0EDF6", "Rose Quartz"),
        ("V20",   "#E2E0ED", "Wisteria"),
        ("BV00",  "#E0DCED", "Mauve Shadow"),
        ("BV11",  "#D4D2E8", "Soft Violet"),
    ]},
    {"category": "soft", "name": "Meadow Pastel",
     "desc": "Pale chlorophyll. Nursery, organic packaging, easter editorial.",
     "colors": [
        ("G000",  "#EAF5ED", "Pale Green"),
        ("YG11",  "#E5F0D0", "Migrate Yellow"),
        ("G12",   "#D2E8C4", "Sea Green"),
        ("YG41",  "#D5EBD4", "Pale Cobalt Green"),
    ]},
    {"category": "soft", "name": "Rosewater",
     "desc": "Three blushes and an ash for grounding. Beauty, florals.",
     "colors": [
        ("E70",  "#EFEAE6", "Ash Rose"),
        ("RV21", "#FDE8E7", "Light Pink"),
        ("R30",  "#FCE3DF", "Pale Yellowish Pink"),
        ("RV13", "#F9C9D7", "Tender Pink"),
    ]},
    {"category": "soft", "name": "Cotton Candy Riot",
     "desc": "Saccharine pastels with no shame. Confection, youth, packaging.",
     "colors": [
        ("Y11",  "#FFFBCC", "Pale Yellow"),
        ("BG02", "#C6E8EA", "New Blue"),
        ("BV20", "#CFDBF1", "Dull Lavender"),
        ("RV02", "#FAD5E6", "Sugared Almond Pink"),
    ]},
    {"category": "soft", "name": "Cherry Blossom Brunch",
     "desc": "Pale petals on porcelain. Hospitality, bakery, spring editorial.",
     "colors": [
        ("E43",  "#E8DABD", "Dull Ivory"),
        ("YG41", "#D5EBD4", "Pale Cobalt Green"),
        ("R20",  "#FCD7CF", "Blush"),
        ("RV02", "#FAD5E6", "Sugared Almond Pink"),
    ]},
    {"category": "soft", "name": "Sun-Bleached Linen",
     "desc": "Heirloom textile in flat morning light. Bridal, lifestyle.",
     "colors": [
        ("W00", "#F3F3EB", "Warm Gray 00"),
        ("E42", "#F3EAD9", "Sand White"),
        ("E55", "#F1DFB9", "Light Camel"),
        ("E71", "#A1847C", "Champagne"),
    ]},
    {"category": "soft", "name": "Heather Field",
     "desc": "Dusty violet on a windward slope. Editorial poetry, ceramics.",
     "colors": [
        ("V12",  "#EED7E9", "Pale Lilac"),
        ("RV52", "#F9CADE", "Cotton Candy"),
        ("V91",  "#E8C4D0", "Pale Grape"),
        ("BV01", "#C4C9E6", "Viola"),
    ]},
    {"category": "soft", "name": "Studio Modernist",
     "desc": "Mid-century supply closet. Branding for thoughtful product.",
     "colors": [
        ("Y23",  "#FBE3B3", "Yellowish Beige"),
        ("R32",  "#FAC1BA", "Peach"),
        ("BV04", "#7C97CE", "Blue Berry"),
        ("W10",  "#302F2B", "Warm Gray 10"),
    ]},
    {"category": "soft", "name": "Sakura Twilight",
     "desc": "Petal pink shifting into night. Editorial poetry, gallery.",
     "colors": [
        ("RV10", "#FDECF4", "Pale Pink"),
        ("RV14", "#F495B7", "Begonia Pink"),
        ("V09",  "#8754A1", "Violet"),
        ("BV29", "#384558", "Slate"),
    ]},

    # ── COOL & ATMOSPHERIC ─────────────────────────────────
    {"category": "cool", "name": "Glacier Mint",
     "desc": "Spa-fresh and clinical. Health tech and minimalist UI.",
     "colors": [
        ("C1",   "#DAE3E8", "Cool Gray 1"),
        ("BG10", "#DCF0EF", "Cool Shadow"),
        ("BG13", "#C4E7E9", "Mint Green"),
        ("B14",  "#71CFEB", "Light Blue"),
    ]},
    {"category": "cool", "name": "Coastal Drift",
     "desc": "Fog, driftwood, slate water. Wellness and editorial calm.",
     "colors": [
        ("E40",  "#F2E8DC", "Brick White"),
        ("B91",  "#D5E2EB", "Pale Grayish Blue"),
        ("BG70", "#DAECEE", "Ocean Mist"),
        ("BG72", "#74B8BB", "Ice Ocean"),
        ("B97",  "#457A9A", "Night Blue"),
    ]},
    {"category": "cool", "name": "Mineral Wash",
     "desc": "Stone, lichen, dried fig. Architectural neutrals with depth.",
     "colors": [
        ("E43",  "#E8DABD", "Dull Ivory"),
        ("BG93", "#BAC1B9", "Green Gray"),
        ("BG78", "#49706B", "Bronze"),
        ("E87",  "#6F604D", "Fig"),
    ]},
    {"category": "cool", "name": "Concrete & Moss",
     "desc": "Brutalist surfaces softened by green. Editorial sci-fi or product.",
     "colors": [
        ("YG91", "#DAD7AE", "Putty"),
        ("BG96", "#81A291", "Anti Blue Green"),
        ("C4",   "#92A0AB", "Cool Gray 4"),
        ("C10",  "#202B31", "Cool Gray 10"),
    ]},
    {"category": "cool", "name": "Aegean Shore",
     "desc": "Whitewash, sea, and afternoon shade.",
     "colors": [
        ("E81",  "#F0E6C2", "Ivory"),
        ("YR21", "#F5DDB1", "Cream"),
        ("B26",  "#65B3E3", "Cobalt Blue"),
        ("BG18", "#37C0B0", "Teal Blue"),
        ("C9",   "#3C474D", "Cool Gray 9"),
    ]},

    # ── EARTH & ORGANIC ────────────────────────────────────
    {"category": "earth", "name": "Botanical Press",
     "desc": "Pressed herbarium specimens on linen card.",
     "colors": [
        ("E81",  "#F0E6C2", "Ivory"),
        ("YG93", "#D2D29C", "Grayish Yellow"),
        ("YG99", "#4E6A15", "Marine Green"),
        ("E29",  "#884636", "Burnt Umber"),
    ]},
    {"category": "earth", "name": "Apothecary",
     "desc": "Amber glass and dried tincture labels.",
     "colors": [
        ("E81",  "#F0E6C2", "Ivory"),
        ("E84",  "#AE9F80", "Khaki"),
        ("E27",  "#997663", "Africano"),
        ("YG67", "#81BF8C", "Moss"),
    ]},
    {"category": "earth", "name": "Espresso Bar",
     "desc": "Crema, cocoa, brown butter. Hospitality and food editorial.",
     "colors": [
        ("E42",  "#F3EAD9", "Sand White"),
        ("YR21", "#F5DDB1", "Cream"),
        ("E29",  "#884636", "Burnt Umber"),
        ("E79",  "#4A2C22", "Cashew"),
    ]},
    {"category": "earth", "name": "Desert Wayfarer",
     "desc": "Sun-warmed clay and field grass. Travel journals, slow editorial.",
     "colors": [
        ("YR23", "#ECCF8B", "Yellow Ochre"),
        ("E33",  "#F3D2B1", "Sand"),
        ("E37",  "#CC9159", "Sepia"),
        ("E29",  "#884636", "Burnt Umber"),
        ("C8",   "#535D66", "Cool Gray 8"),
    ]},
    {"category": "earth", "name": "Forest Floor",
     "desc": "Damp loam under canopy. Outdoor brands, nature publishing.",
     "colors": [
        ("E81",  "#F0E6C2", "Ivory"),
        ("YR23", "#ECCF8B", "Yellow Ochre"),
        ("YG67", "#81BF8C", "Moss"),
        ("G29",  "#197C5D", "Pine Tree Green"),
        ("E49",  "#634C3C", "Dark Bark"),
    ]},
    {"category": "earth", "name": "Terracotta Suite",
     "desc": "Mediterranean tile and bisque. Hospitality and architectural work.",
     "colors": [
        ("E42",  "#F3EAD9", "Sand White"),
        ("YR12", "#FFE2A6", "Loquat"),
        ("E07",  "#CC816A", "Light Mahogany"),
        ("E19",  "#C45238", "Redwood"),
        ("E97",  "#B46034", "Deep Orange"),
    ]},

    # ── MOODY & SOPHISTICATED ──────────────────────────────
    {"category": "moody", "name": "Iris Library",
     "desc": "Bound volumes and morocco leather. Academic, publishing, archival.",
     "colors": [
        ("E81",  "#F0E6C2", "Ivory"),
        ("Y26",  "#F0DD67", "Mustard"),
        ("E47",  "#8A6E59", "Dark Brown"),
        ("V25",  "#857FAD", "Pale Blackberry"),
        ("B79",  "#3B479D", "Iris"),
    ]},
    {"category": "moody", "name": "Velvet Lounge",
     "desc": "Bourbon, oxblood, lamplight. Restaurant, masthead, podcast art.",
     "colors": [
        ("YR14", "#FEC84E", "Caramel"),
        ("R89",  "#7D2B42", "Dark Red"),
        ("E89",  "#5A4939", "Pecan"),
        ("V99",  "#524358", "Aubergine"),
    ]},
    {"category": "moody", "name": "Midnight Atelier",
     "desc": "Velvet, brass, and ink. Luxury editorial and fashion.",
     "colors": [
        ("E81",  "#F0E6C2", "Ivory"),
        ("R89",  "#7D2B42", "Dark Red"),
        ("E79",  "#4A2C22", "Cashew"),
        ("V99",  "#524358", "Aubergine"),
        ("BV29", "#384558", "Slate"),
    ]},

    # ── BOLD & SATURATED ───────────────────────────────────
    {"category": "bold", "name": "Coral Reef",
     "desc": "Tropical and amphibious. Travel, beauty, swimwear.",
     "colors": [
        ("YR16", "#FEB729", "Apricot"),
        ("R05",  "#F6917B", "Salmon Red"),
        ("RV04", "#F6A3BF", "Shock Pink"),
        ("BG18", "#37C0B0", "Teal Blue"),
    ]},
    {"category": "bold", "name": "Tangerine Dream",
     "desc": "Sunset on a record sleeve. Music, surf, vintage technicolor.",
     "colors": [
        ("E40",  "#F2E8DC", "Brick White"),
        ("E04",  "#E4BCC4", "Lipstick Natural"),
        ("YR04", "#FEC369", "Chrome Orange"),
        ("YR07", "#F26F39", "Cadmium Orange"),
        ("V06",  "#CE95C2", "Lavender"),
    ]},
    {"category": "bold", "name": "Citrus Grove",
     "desc": "Squeezed, peeled, sliced. Food, fitness, summer campaigns.",
     "colors": [
        ("E40",  "#F2E8DC", "Brick White"),
        ("Y15",  "#FEE96C", "Cadmium Yellow"),
        ("YG07", "#A5CF4F", "Acid Green"),
        ("G07",  "#7BC576", "Nile Green"),
        ("YR68", "#F37022", "Orange"),
    ]},
    {"category": "bold", "name": "Bauhaus Pop",
     "desc": "Primary geometry. Graphic design, posters, education.",
     "colors": [
        ("E0000", "#FFFAF4", "Floral White"),
        ("Y08",   "#FEF200", "Acid Yellow"),
        ("R29",   "#ED174B", "Lipstick Red"),
        ("B29",   "#0177C1", "Ultramarine"),
        ("N10",   "#312F30", "Neutral Gray 10"),
    ]},
    {"category": "bold", "name": "Jazz Club",
     "desc": "Stage lights against velvet curtain. Music, nightlife, editorial.",
     "colors": [
        ("E0000", "#FFFAF4", "Floral White"),
        ("Y17",   "#FFE455", "Golden Yellow"),
        ("R29",   "#ED174B", "Lipstick Red"),
        ("B69",   "#2165AE", "Stratospheric Blue"),
        ("N10",   "#312F30", "Neutral Gray 10"),
    ]},
    {"category": "bold", "name": "Punk Confetti",
     "desc": "All four Copic fluorescents at full volume.",
     "colors": [
        ("FY1",  "#FFF697", "Fluorescent Yellow Orange"),
        ("FYR1", "#FECC99", "Fluorescent Orange"),
        ("FRV1", "#F5A3C7", "Fluorescent Pink"),
        ("FV2",  "#7F74B6", "Fluorescent Dull Violet"),
        ("N10",  "#312F30", "Neutral Gray 10"),
    ]},
]
